[project]
name = "webscrap_flask"
version = "1.0.0"
dependencies = [
  "flask",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["webscrap_flask"]